version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2002Pelusa14190-
      MYSQL_DATABASE: boardang_login
    ports:
      - "3306:3306"
    networks:
      - boardang-network

  spring-app:
    image: boardang-app:latest
    container_name: boardang-app
    build:
      context: .
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/boardang_login?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 2002Pelusa14190-
    ports:
      - "8080:8080"
    networks:
      - boardang-network

networks:
  boardang-network:
    driver: bridge
